name: someWF
on:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  uJob:
    name: uJob
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5.5.0
        with:
          go-version: "1.20"

      - name: Build Go Binary
        run: go build -o main main.go

      - name: Run binary
        run: ./main

  mJob:
    name: mJob
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5.5.0
        with:
          go-version: "1.20"

      - name: Build Go Binary
        run: go build -o main main.go

      - name: Run binary
        run: ./main

  wJob:
    name: wJob
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5.5.0
        with:
          go-version: "1.20"

      - name: Build Go Binary
        run: go build -o main.exe main.go

      - name: Run binary
        run: .\main.exe

  job4:
    name: allJob
    needs: [uJob, mJob, wJob]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5.5.0
        with:
          go-version: "1.20"

      - name: Cross-compile for all platforms
        run: |
          echo "Cross compiling for all platforms:"
          GOOS=linux GOARCH=amd64 go build -o main-linux main.go
          GOOS=windows GOARCH=amd64 go build -o main-windows.exe main.go
          GOOS=darwin GOARCH=amd64 go build -o main-macos-intel main.go

